### PR TITLE
Avoid usage of jdk.jconsole module in Java 9+

### LINKED ISSUE #48: Does not build or run with java9
Tried with Java9.0.4

Build time error:
[INFO] Running org.cyclopsgroup.jmxterm.pm.JConsoleClassLoaderFactoryTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.049 s <<< FAILURE! - in org.cyclopsgroup.jmxterm.pm.JConsoleClassLoaderFactoryTest
[ERROR] testLoad(org.cyclopsgroup.jmxterm.pm.JConsoleClassLoaderFactoryTest)  Time elapsed: 0.012 s  <<< ERROR!
java.lang.RuntimeException: Operation requires JDK instead of JRE
	at org.cyclopsgroup.jmxterm.pm.JConsoleClassLoaderFactoryTest.testLoad(JConsoleClassLoaderFactoryTest.java:22)

Runtime error:
:~/Downloads$ java -jar jmxterm-1.0.0-uber.jar 
java.lang.NullPointerException
	at org.codehaus.classworlds.Launcher.getEnhancedMainMethod(Launcher.java:195)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:294)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.bootstrap(Bootstrapper.java:209)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.main(Bootstrapper.java:116)

### LINKED ISSUE #87: WARNING: An illegal reflective access operation has occurred
Hi.
I am getting following warnings while connecting to the jxm console:
$ java -jar /vendor/jmxterm/jmxterm-1.0.2-uber.jar -l 119511
Delete /u01/app/home/asmsadm/.jmxterm_history if you encounter error right after launching me.WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.cyclopsgroup.jmxterm.utils.WeakCastUtils$2 (file:/vendor/jmxterm/jmxterm-1.0.2-uber.jar) to method sun.tools.jconsole.LocalVirtualMachine.getAllVirtualMachines()
WARNING: Please consider reporting this to the maintainers of org.cyclopsgroup.jmxterm.utils.WeakCastUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Welcome to JMX terminal. Type "help" for available commands.
$>Fri Sep 25 15:18:45 EDT 2020: Connected nj01smgapp5061.smg.iconectiv.com
/
#IllegalArgumentException: Command / isn't valid, run help to see available commands
$>
$>

### PR DESCRIPTION
**Pull request by nyg**
Hello,

Since Java 9, there is a warning (illegal reflective access operation) when using the jdk.jconsole module which contains classes like `LocalVirtualMachine` that are used to list local VMs and attach to them. On later Java version (17?), accessing these classes makes jmxterm crash.

I implemented a `Jdk9JavaProcessManager` which relies only on the public Attach API (which is actually what `LocalVirtualMachine` appears to use under the hood, see: https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/sun/tools/jconsole/LocalVirtualMachine.java#L123). So my code is voluntarily based on what goes on in LocalVirtualMachine (especially when listing VMs).

I had to adapt `WeakCastUtils` to build the `methodMap` using not the `from` instance (which in Jdk9 case is an instance of `VirtualMachineImpl` which is not part of the public API) but using the "original" interface, i.e. `VirtualMachine`. When this distinction is not needed, I just use `from.getClass()`.

The source and target version remain Java 8.

Also, as the mininum Java version is 8, I'm not sure it's useful to keep `Jdk5JavaProcessManager`.

If `WeakCastUtils` doesn't serve any other purpose than supporting multiple Java version, probably it could be replaced with Java 9 multi-release JARs: https://nipafx.dev/multi-release-jars-multiple-java-versions/.

Note 1: this PR includes my other PR (#112).

Note 2: as I answered in #48, making jmxterm work with Java 17+ can be done by allowing access to the jdk.jconsole module (with `--add-exports jdk.jconsole/...`) but this is not supported by Java 8 and cannot be used with the Java 9 `--release` option.

Best,
nyg

Fixes #48
Fixes #87

EDIT: I tested in the following way: compiled and ran (running `jvms` and `open`) jmxterm with both JDK8 and JDK21, but always leaving the maven.compiler.source and target to 1.8.

### CODE REVIEW

**Review by jiaqi — APPROVED** [review]

File: src/main/java/org/cyclopsgroup/jmxterm/jdk9/Jdk9JavaProcess.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+  public boolean isManageable() {
+    return address != null;
+  }
+
+  @Override
+  public void startManagementAgent() throws IOException {
+    Object vm = staticVirtualMachine.attach(vmd.id());
+    try {
+      Class<?> originalVirtualMachine = Class.forName(VirtualMachine.ORIGINAL_CLASS_NAME);
+      VirtualMachine vmProxy = WeakCastUtils.cast(originalVirtualMachine, VirtualMachine.class);
```
Comment (tachun-shen-appier) [inline src/main/java/org/cyclopsgroup/jmxterm/jdk9/Jdk9JavaProcess.java:52]: Did you forget to pass `vm` to `cast`?

**Comment by jluehe** [comment]
@nyg, have you ever seen this exception when running with JDK 21:

```
Exception in thread "main" java.lang.RuntimeException: Can't cast sun.tools.attach.AttachProviderImpl@272113c4: 4089615 to VirtualMachineDescriptor
        at org.cyclopsgroup.jmxterm.jdk9.Jdk9JavaProcess.startManagementAgent(Jdk9JavaProcess.java:55)
        at org.cyclopsgroup.jmxterm.SyntaxUtils.getUrl(SyntaxUtils.java:46)
        at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:135)
        at org.cyclopsgroup.jmxterm.boot.CliMain.main(CliMain.java:41)
Caused by: java.lang.NoSuchMethodException: java.lang.Class.startLocalManagementAgent()
        at java.base/java.lang.Class.getMethod(Class.java:2395)
        at org.cyclopsgroup.jmxterm.utils.WeakCastUtils.cast(WeakCastUtils.java:43)
        at org.cyclopsgroup.jmxterm.utils.WeakCastUtils.cast(WeakCastUtils.java:116)
        at org.cyclopsgroup.jmxterm.utils.WeakCastUtils.cast(WeakCastUtils.java:81)
        at org.cyclopsgroup.jmxterm.jdk9.Jdk9JavaProcess.startManagementAgent(Jdk9JavaProcess.java:52)
        ... 3 more
```
